### ISSUE TITLE
Do I really need provisionedConcurrency to autoscaling?

### ISSUE THREAD

**Issue by lusatiro** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#20]
> You must provide atleast provisionedConcurrency and concurrencyAutoscaling to enable autoscaling. Set concurrencyAutoscaling to a boolean, or object with configuration. Any omitted configuration will use module defaults.

It leads to believing we need both to autoscaling. `concurrencyAutoscaling` enabled is not enough? as far as I know, `provisionedConcurrency` is only for keeping a number of environments waiting for requests in order not to have cold starts.

**Comment by claydanford** [comment]
Hi @lusatiro, Yes both are required for autoscaling.

`provisionedConcurrency`, built into the framework, adds a lambda alias with provisioned concurrency enabled.

`concurrencyAutoscaling` adds target tracking autoscaling policies to scale up/down that provisioned concurrency number based on load.

Autoscaling is tied to the provisionedConcurrency since it needs that alias to set the target in the policies.

HTH,

CRD
