### ISSUE TITLE
New upgrade of resources names breaking existing deployments

### ISSUE THREAD

**Issue by yuvalyacoby** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#43]
New minor upgrade `1.8.0` of normalizing resources names breaks current deployments.
Cloudformation failed with CREATE_FAILED.

For example:
Logical ID `BcexplorerdevelopResourcesmetadataAutoScalingPolicyDevUswest2` turned to `ResourcesmetadataAutoScalingTarget` after plugin upgrade. Since `BcexplorerdevelopResourcesmetadataAutoScalingPolicyDevUswest2` already exists and point to same physical id, the new creation of `ResourcesmetadataAutoScalingTarget` fails with 
function:bc-explorer-resources-metadata-develop:provisioned|lambda:function:ProvisionedConcurrency|lambda already exists in stack arn:aws:cloudformation:us-west-2:*****:stack/bc-explorer-develop/bc****

Currently I downgraded version.

**Comment by cookieMr** [comment]
@claydanford we confirmed this issue here in our project
this change actually is a breaking contract change; whole stack needs to be recreated
as a workaround we are downgrading version to `1.7.0` with no `^` (to avoid minor/patch version updates)

**Comment by claydanford** [comment]
Hi @yuvalyacoby @cookieMr, Seems I am unable to unpublish in npm since we already have a lot of folks using this version. There are some options here, and I want to hear your thoughts:

1. Publish version 2.0.0 as a change-breaking version, but it will leave 1.8.0 as the latest 1.x.x
2. Publish 1.9.0 and roll back those changes so the latest will not have a breaking change
3. Both 1 and 2.

To fix this without rolling back, you'll have to remove provisioned concurrency autoscaling from your service, deploy, and then add it back. This is not great for applications that have a lot of services or long deployment processes.

**Comment by yuvalyacoby** [comment]
@claydanford I would personally favor option 2, because I would like to keep up tp date with future versions of the plugin (which is great BTW, thank you), and would prefer to avoid deploying without autoscaling and then re-dploy with new naming.

What is the value/purpose of matching the names to sls? If it's something you want to go with and have real value, than I guess we can go with the hassle of the re-deployments, and in that case I believe option 3 is better, so others won't face this breaking change when auto-upgrading minor versions (if they haven't yet)
